/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.tfedorov.icebergdemo

import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.must.Matchers
import org.scalatest.matchers.should.Matchers.convertToAnyShouldWrapper

//@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFreeSpec with Matchers {

  "Test generateOptimizeTableProc without Predicates" in {
    2 + 2 shouldEqual 5
  }
}
